CREATE DATABASE CHICAGO;

USE CHICAGO;

-- DROP TABLE CENSUS;
CREATE TABLE CENSUS(
					COMMUNITY_AREA_NUMBER INT NOT NULL, 
					COMMUNITY_AREA_NAME VARCHAR(25),
					PERCENT_OF_HOUSING_CROWDED DECIMAL(10,2),
					PERCENT_HOUSEHOLDS_BELOW_POVERTY DECIMAL(10,2),
                    PERCENT_AGED_OVER_16_UNEMPLOYED DECIMAL(10,2),
                    PERCENT_AGED_OVER_25_WITHOUT_HIGH_SCHOOL_DIPLOMA DECIMAL(10,2),
                    PERCENT_AGED_UNDER_18_OR_OVER_64 DECIMAL(10,2),
                    PER_CAPITA_INCOME INT,
                    HARDSHIP_INDEX INT,
					PRIMARY KEY (COMMUNITY_AREA_NUMBER));
                    
LOAD DATA INFILE 'Census_Data_Chicago.csv' 
INTO TABLE CENSUS
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- SELECT * FROM CENSUS;

-- DROP TABLE CRIME;
CREATE TABLE CRIME(
				ID BIGINT NOT NULL,
                CASE_NUMBER VARCHAR(20),
                DATE VARCHAR(40),
                BLOCK VARCHAR(40),
                IUCR INT,
                PRIMARY_TYPE VARCHAR(30),
                DESCRIPTION VARCHAR(20),
                LOCATION_DESCRIPTION VARCHAR(40),
                ARREST VARCHAR(25),
                DOMESTIC VARCHAR(15),
                BEAT VARCHAR(15),
                DISTRICT INT,
                WARD INT,
                COMMUNITY_AREA_NUMBER INT,
                FBICODE INT,
                X_COORDINATE BIGINT,
                Y_COORDINATE BIGINT,
                YEAR INT,
                UPDATEDON VARCHAR(30),
                LATITUDE VARCHAR(20),
                LONGITUDE VARCHAR(20),
                LOCATION VARCHAR(60),
                PRIMARY KEY (ID));
                
LOAD DATA INFILE 'Chicago_Crime_Data.csv' 
INTO TABLE CRIME
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

-- SELECT * FROM CRIME;

-- DROP TABLE PUBLIC_SCHOOLS;
CREATE TABLE PUBLIC_SCHOOLS(
				SCHOOL_ID BIGINT NOT NULL,
                NAME_OF_SCHOOL VARCHAR(50),
                ELEMENTARY_MIDDLE_OR_HIGH_SCHOOL VARCHAR(10),
                STREET_ADDRESS VARCHAR(50),
                CITY VARCHAR(50),
                STATE VARCHAR(10),
                ZIP_CODE VARCHAR(20),
                PHONE_NUMBER VARCHAR(20),
                LINK VARCHAR(200),
                NETWORK_MANAGER VARCHAR(50),
                COLLABORATIVE_NAME VARCHAR(50),
                ADEQUATE_YEARLY_PROGRESS_MADE VARCHAR(50),
                TRACK_SCHEDULE VARCHAR(50),
                CPS_PERFORMANCE_POLICY_STATUS VARCHAR(50),
                CPS_PERFORMANCE_POLICY_LEVEL VARCHAR(50),
                HEALTHY_SCHOOL_CERTIFIED VARCHAR(50),
                SAFETY_ICON VARCHAR(50),
                SAFETY_SCORE INT,
                FAMILY_INVOLVEMENT_ICON VARCHAR(20),
                FAMILY_INVOLVEMENT_SCORE INT,
                ENVIRONMENT_ICON VARCHAR(50),
                ENVIRONMENT_SCORE INT,
                INSTRUCTION_ICON VARCHAR(50),
                INSTRUCTION_SCORE INT,
                LEADERS_ICON VARCHAR(50),
                LEADERS_SCORE INT,
                TEACHERS_ICON VARCHAR(50),
                TEACHERS_SCORE INT,
                PARENT_ENGAGEMENT_ICON VARCHAR(50),
                PARENT_ENGAGEMENT_SCORE INT,
                PARENT_ENVIRONMENT_ICON VARCHAR(50),
                PARENT_ENVIRONMENT_SCORE INT,
                AVERAGE_STUDENT_ATTENDANCE VARCHAR(20),
                RATE_OF_MISCONDUCTS_PER_100_STUDENTS INT,
                AVERAGE_TEACHER_ATTENDANCE VARCHAR(20),
                INDIVIDUALIZED_EDUCATION_PROGRAM_COMPLIANCE_RATE VARCHAR(20),
                PK_2_LITERACY_RATE DECIMAL(10,2),
                PK_2_MATH_RATE DECIMAL(10,2),
                GR_3_5_GRADE_LEVEL_MATH_RATE DECIMAL(10,2),
                GR_3_5_GRADE_LEVEL_READ_RATE DECIMAL(10,2),
                GR_3_5_KEEP_PACE_READ_RATE DECIMAL(10,2),
                GR_3_5_KEEP_PACE_MATH_RATE DECIMAL(10,2),
                GR_6_8_GRADE_LEVEL_MATH_RATE DECIMAL(10,2),
                GR_6_8_GRADE_LEVEL_READ_RATE DECIMAL(10,2),
                GR_6_8_KEEP_PACE_MATH_RATE DECIMAL(10,2),
                GR_6_8_KEEP_PACE_READ_RATE DECIMAL(10,2),
                GR_8_EXPLORE_MATH_RATE DECIMAL(10,2),
                GR_8_EXPLORE_READ_RATE DECIMAL(10,2),
                ISAT_EXCEEDING_MATH_RATE DECIMAL(10,2),
                ISAT_EXCEEDING_READING_RATE DECIMAL(10,2),
                ISAT_VALUE_ADD_MATH DECIMAL(10,2),
                ISAT_VALUE_ADD_READ DECIMAL(10,2),
                ISAT_VALUE_ADD_COLOR_MATH VARCHAR(20),
                ISAT_VALUE_ADD_COLOR_READ VARCHAR(20),
				STUDENTS_TAKING_ALGEBRA_RATE DECIMAL(10,2),
                STUDENTS_PASSING_ALGEBRA_RATE DECIMAL(10,2),
                NINTH_GRADE_EXPLORE_2009 VARCHAR(15),
                NINTH_GRADE_EXPLORE_2010 VARCHAR(15),
                TENTH_GRADE_PLAN_2009 VARCHAR(15),
                TENTH_GRADE_PLAN_2010 VARCHAR(15),
                NET_CHANGE_EXPLORE_AND_PLAN VARCHAR(15),
                ELEVENTH_GRADE_AVERAGE_ACT_2011 VARCHAR(15),
                NET_CHANGE_PLAN_AND_ACT VARCHAR(15),
                COLLEGE_ELIGIBILITY VARCHAR(15),
                GRADUATION_RATE VARCHAR(15),
                COLLEGE_ENROLLMENT_RATE VARCHAR(15),
                COLLEGE_ENROLLMENT INT,
                GENERAL_SERVICES_ROUTE INT,
                FRESHMAN_ON_TRACK_RATE VARCHAR(15),
                X_COORDINATE DECIMAL(10,3),
                Y_COORDINATE DECIMAL(10,3),
                LATITUDE DECIMAL(10,10),
                LONGITUDE DECIMAL(10,10),
                COMMUNITY_AREA_NUMBER INT,
                COMMUNITY_AREA_NAME VARCHAR(30),
                WARD INT,
                POLICE_DISTRICT INT,
                LOCATION VARCHAR(60),
                PRIMARY KEY (SCHOOL_ID));

LOAD DATA INFILE 'Chicago_Public_Schools.csv' 
INTO TABLE PUBLIC_SCHOOLS
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 2 ROWS;

-- SELECT * FROM PUBLIC_SCHOOLS;

